### ISSUE TITLE
Charge limit is named as <car_name>_soc_limit in 1.3.0 

### ISSUE THREAD

**Issue by HappyZ** [spiffyvmlab/homeassistant#2]
`sensor.r1s_soc_limit` or `sensor.r1t_soc_limit` if you use https://github.com/bretterer/home-assistant-rivian/releases/tag/1.3.0

**Comment by HappyZ** [comment]
also

_tire_pressure_front_left_validity
_tire_pressure_front_right_validity
etc.

instead of
_tire_pressure_front_left_status
_tire_pressure_front_right_status
etc.

**Comment by spiffyvmlab** [comment]
> also
> 
> binary_sensor.<r1s/r1t>_tire_pressure_front_left_validity binary_sensor.<r1s/r1t>_tire_pressure_front_right_validity etc.
> 
> instead of sensor.<r1s/r1t>_tire_pressure_front_left_status sensor.<r1s/r1t>_tire_pressure_front_right_status etc.
> 
> I used sensor.<r1s/r1t>_tire_pressure_rear_left_2 instead etc

I hadn't seen that change. Good catch!. I think the soc sensor will be subjective. Mine is still `sensor.r1t_battery_state_of_charge_limit`, but all of these sensor names can be different from one implementation to another, depending if users change them manually, or just use the default from the integration.

For the tire pressure ones, I'm ignoring the validity `binary_sensor`, and just using the `sensor`, since the `sensor` on is what reports "OK" (not sure what the "bad" value is, since I've never seen it, but technically that one could/should be a binary sensor, if it only reports "OK" or "Not OK". The fact that it's not a binary sensor makes me think _maybe_ it reports High, Low, or OK, but I'm not sure.
